framework:
    workflows:
        comment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Comment
            initial_marking: submitted
            places:
                - submitted
                - ham
                - spam
                - rejected
                - published
            transitions:
                accepts:
                    from: submitted
                    to: ham
                reject_spam:
                    from: submitted
                    to: spam
                publish:
                    from: ham
                    to: published
                reject:
                    from: ham
                    to: rejected

